### PR TITLE
test(google): add post-deploy test for google

### PR DESCRIPTION
**Pull request by trieloff**

### CODE REVIEW

**Comment by trieloff** [comment]
Depends on https://github.com/adobe/helix-ops/pull/187 and CircleCI changes.

**Review by tripodsan — APPROVED** [review]

**Comment by trieloff** [comment]
The Google Deploy is failing right now:

```
GoogleError: Build failed: npm ERR! Cannot read property '@google-cloud/secret-manager' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /builder/home/.npm/_logs/2021-03-16T12_27_05_700Z-debug.log; Error ID: beaf8772
```

**Comment by trieloff** [comment]
Ticket opened with GCP support.

**Comment by trieloff** [comment]
I'm currently blocked by adobe/helix-deploy#170, but Google support says:

> I noticed two things when working with your code:
>
> 1) I haven't been able to run it on my local environment which points me to a coding issue, if you could share with me how are you running it in your local environment this can help me to try running it again and discard or confirm this.
> 
> 2) when running it in cloud functions I tested the package.json with a lot simpler app and it worked fine therefore the package.json is correct, also I Tried to run your code on a cloud function and even deleting the explicit usages of the secret manage client library it was giving me the same error therefore I would suggest to check that the dependencies have their dependencies well managed, as this points me that a dependency is using it without loading it.  

This does not really explain why the test functions in helix-deploy do work, but I hope to be able to compare the output when helix-deploy builds again.

**Comment by trieloff** [comment]
After [some digging](https://cloud.google.com/functions/docs/building/pack#building_your_function_2) I can at least reproduce the error and found the issue.

But step by step: the build pack is running:

1. `npm install --package-lock-only --quiet`
2. `npm ci --quiet` which fails with

```
npm ERR! Cannot read property '@google-cloud/secret-manager' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cnb/.npm/_logs/2021-03-23T10_49_44_891Z-debug.log
Done "npm ci --quiet (NODE_ENV=production)" (468.558499ms)
Failure: (ID: beaf8772) npm ERR! Cannot read property '@google-cloud/secret-manager' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cnb/.npm/_logs/2021-03-23T10_49_44_891Z-debug.log
```

So what happens in `npm install --package-lock-only`?

```
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN Invalid version: "ci999"
npm WARN helix-services No description
npm WARN helix-services No repository field.
npm WARN helix-services No README data
npm WARN helix-services No license field.

up to date in 0.527s
found 0 vulnerabilities
```

Just warnings, right?

Let's take a look at the generated `package-lock.json`

```json
{
  "name": "status",
  "version": "ci999",
  "lockfileVersion": 1
}
```

A bit empty. And no `"dependencies": {}`, hence the `Cannot read property '@google-cloud/secret-manager' of undefined`

Turns out, one of the warnings is more serious than the others: `npm WARN Invalid version: "ci999"`

Change `"version": "ci999"` to `"version": "1.1.1"` and it works like a charm. Interestingly, the version in my test case https://github.com/adobe/helix-deploy/pull/167/files#diff-8436defe5ac92dd08b3482b61ec1a2623afa4924a9a602475c8e39436ad17378R3 is a valid semver version, which explains why it works in the test, but not here.

Removing the `version` from `package.json` works just as well. 🤦 

So the fix is not to allow non-semver version numbers slip into the `package.json ` generated by `helix-deploy`

**Pull request merged**
